#!/bin/bash
MANPAGE=aptitude.pl.8

#Polish left quotation mark
sed -i -e 's_(lq_[Bq]_g' $MANPAGE

sed -i 's_\\fBaptitude\\fR help_\\fBaptitude\\fR \\fBhelp\\fR_' $MANPAGE
sed -i 's_^\.SH "NAME"_.SH "NAZWA"_' $MANPAGE
sed -i 's_^\.SH "SYNOPSIS"_.SH "SKŁADNIA"_' $MANPAGE
sed -i 's_^\.SH "DESCRIPTION"_.SH "OPIS"_' $MANPAGE
sed -i 's_^\.SH "AUTHOR"_.SH "AUTOR"_' $MANPAGE
sed -i 's_^\.SH "COPYRIGHT"_.SH "PRAWA AUTORSKIE"_' $MANPAGE
sed -i 's_Note_Uwaga_' $MANPAGE
sed -i 's_Author._ Autor._' $MANPAGE
sed -i s_'Example\ \&10.'_'Przykład -'_ $MANPAGE

cp $MANPAGE ${MANPAGE}.tmp
cat ${MANPAGE}.tmp - >$MANPAGE <<EOF

.SH "TŁUMACZENIE"
Pierwsze tłumaczenie, którego ostatnia wersja pochodzi z 2000 roku, wykonał Michał Politkowski <l10n@mp.pl.eu.org>. W 2012 tłumaczenie zaktualizował i uzupełnił Michał Kułach <michal.kulach@gmail.com>.

EOF
rm ${MANPAGE}.tmp
