Import('base_env')

base_env.Dist(
    'SConscript',
    'aptitude_build.py',
    'aptitude_configure.py',
    'aptitude_configure_checks.py',
    'aptitude_configure_utils.py'
    )

SConscript(dirs = [
        'site_tools'
        ])
