.\" Title: \fBaptitude-run-state-bundle\fR
.\" Author: Daniel Burrows <dburrows@debian.org>
.\" Date: 7/8/2007
.TH "\f8APTITUDE-RUN-STATE-BUNDLE\fR" "1" "7/8/2007" "aptitude-run-state-bundle" "aptitude utilities"
.SH "NAME"
aptitude-run-state-bundle \- unpack an aptitude state bundle and
invoke aptitude on it
.SH "SYNOPSIS"
\fBaptitude-run-state-bundle\fR [<\fIoptions\fR> ...] <input-file>
[<program> [<\fIprogram-arguments\fR> ...]]
.SH "DESCRIPTION"
.PP
\fBaptitude-run-state-bundle\fR unpacks the given aptitude state
bundle created by \fBaptitude-create-state-bundle\fR(1) to a temporary
directory, invokes \(lq\fBprogram\fR\(rq on it with the supplied
arguments, and removes the temporary directory afterwards.  If
\(lq\fBprogram\fR\(rq is not supplied, it defaults to
\fBaptitude\fR(8).
.SH "OPTIONS"
.PP
The following options may occur on the command-line before the input
file.  Options following the input file are presumed to be arguments
to aptitude.
.PP
\fB--help\fR
.RS
Display a brief usage summary.
.RE
\fB--no-clean\fR
.RE
.RS
Do not remove the unpacked state directory after running
\fBaptitude\fR.  You might want to use this if, for instance, you are
debugging a problem that appears when aptitude's state file is
modified.  When \fBaptitude\fR finishes running, the name of the state
directory will be printed so that you can access it in the future.
.PP
This option is enabled automatically by \fB--statedir\fR.
.RE
.PP
\fB--really-clean\fR
.RS
Delete the state directory after running \fBaptitude\fR, even if
\fB--no-clean\fR or \fB--statedir\fR was supplied.
.RE
.PP
\fB--statedir\fR
.RS
Instead of treating the input file as a state bundle, treat it as an
unpacked state bundle.  For instance, you can use this to access the
state directory that was created by a prior run with \fB--no-clean\fR.
.RE
.PP
\fB--unpack\fR
.RS
Unpack the input file to a temporary directory, but don't actually run
\fBaptitude\fR.
.RE
.SH "SEE ALSO"
.PP
\fBaptitude-create-state-bundle\fR(1), \fBaptitude\fR(8), \fBapt(8)\fR
.SH "AUTHOR"
.PP
\fBDaniel Burrows\fR <\&dburrows@debian.org\&>
.SH "COPYRIGHT"
.PP
Copyright 2007 Daniel Burrows.

aptitude-run-state-bundle and its manpage may be copied, modified, and
redistributed in any manner whatsoever.
