.\"                                      Hey, EMACS: -*- nroff -*-
.\" Translator: Micha³ Politowski <l10n@mp.pl.eu.org>
.\"
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH APTITUDE 8 "9/8/00"
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAZWA
aptitude \- interfejs wysokiego poziomu dla mened¿era pakietów.
.SH SK£ADNIA
.B aptitude [ \-S
\fIplik\fR
.B ] [ \-u | \-i ]

.B aptitude [
\fIopcje\fR
.B ] [ update | upgrade | forget-new | clean | autoclean ]

.B aptitude [
\fIopcje\fR
.B ] [ remove | hold | purge | markauto | unmarkauto | dist-upgrade ] pakiety...

.B aptitude [
\fIopcje\fR
.B ] search wzorce...

.B aptitude [
\fIopcje\fR
.B ] download pakiety...
.SH OPIS
.B aptitude
jest tekstowym interfejsem do systemu pakietów dystrybucji Debian GNU/Linux.

Pozwala u¿ytkownikowi przegl±daæ listê pakietów i wykonywaæ zadania
zwi±zane z zarz±dzaniem nimi, takie jak instalowanie, uaktualnianie czy usuwanie.
Zadania te mo¿na wykonywaæ w trybie interaktywnym lub z wiersza poleceñ.

.SH WIERSZ POLECEÑ

Pierwszy argument nie zaczynaj±cy siê znakiem minus ("-") jest traktowany jako
akcja, któr± ma wykonaæ program. Je¶li akcja nie zostanie podana w wierszu poleceñ
aptitude startuje w trybie interaktywnym.

Dostêpne s± nastêpuj±ce akcje:

.TP
.B install
Instaluje pakiety. Nazwy pakietów nale¿y podaæ po poleceniu "install".
Nazwy zawieraj±ce znak "~" bêd± traktowane jak wzorce wyszukiwania
i spowoduj± zainstalowanie wszystkich pasuj±cych pakietów.

Dodanie na koñcu nazwy znaku "-", "+", "_" lub "=" spowoduje, ¿e
pakiety zostan± odpowiednio usuniête, zainstalowane, wyczyszczone lub wstrzymane.
Mo¿na to wykorzystaæ na przyk³ad do przeprowadzenia z wiersza poleceñ wielu ró¿nych akcji
na raz.

Jako szczególny przypadek, "install" bez dodatkowych argumentów przeprowadzi
wszystkie zaplanowane wcze¶niej akcje.

UWAGA: Polecenie "install" modyfikuje zapisane informacje o zaplanowanych akcjach.
Dlatego po wydaniu komendy "aptitude install foo bar" i przerwaniu nastêpnie
instalacji nale¿y uruchomiæ np. "aptitude remove foo bar" aby odwo³aæ to polecenie.

.TP
.B remove, purge, hold
Te polecenia dzia³aj± podobnie do "install", ale wykonuj± odpowiednio
usuniêcie, wyczyszczenie lub wstrzymanie pakietów o ile nie podano inaczej.

(Na przyk³ad "aptitude remove '~ndeity'" usunie wszystkie pakiety, których nazwa
zawiera ci±g "deity".)

.TP
.B markauto, unmarkauto
Zaznaczaj± pakiety jako odpowiednio automatycznie lub rêcznie zainstalowane.
Mo¿na podawaæ pakiety korzystaj±c z tej samej sk³adni co dla poprzednich poleceñ,
w³±czj±c w to specyfikacjê akcji do wykonania.
Na przyk³ad "aptitude markauto '~slibs'" zaznaczy wszystkie pakiety w sekcji
"libs" jako zainstalowane automatycznie.

.TP
.B update
Uaktualnia listê dostêpnych pakietów danymi z serwerów.
(Równowa¿ne "apt-get update".)

.TP
.B upgrade
Uaktualnia zainstalowane pakiety do najnowszych wersji.
Zainstalowane pakiety nie s± usuwane, chyba, ¿e nie s± u¿ywane.
¯adne niezainstalowane pakiety nie s± instalowane.

Je¶li pakietu nie mo¿na uaktualniæ bez naruszania tych ograniczeñ
nie zostaje uaktualniony.

.TP
.B forget-new
Usuwa informacje, które pakiety s± nowe (równowa¿ne wci¶niêciu "f"
w trybie interaktywnym).

.TP
.B search
Wyszukuje pakiety pasuj±ce do wzorców podanych po poleceniu.
Zostan± wypisane wszystkie pakiety pasuj±ce do tych wzorców.
Na przyk³ad "aptitude search '~N'" poka¿e wszystkie nowe pakiety.

.TP
.B clean
Usuwa wszystkie pobrane pliki pakietów.

.TP
.B autoclean
Usuwa pobrane pliki pakietów, które nie s± ju¿ dostêpne.

.TP
.B download
Pobiera do bie¿±cego katalogu plik .deb najnowszej wersji podanego pakietu.

.P

Nastêpuj±ce argumenty zaczynaj±ce siê od znaku minus
okre¶laj± akcje dla trybu interaktywnego. S± one jednak u¿ywane wewnêtrznie przez program
i nie powinna zaj¶æ potrzeba samodzielnego ich podawania.

.TP
.B \-S \fIplik\fR
Wczytuje z \fIpliku\fR rozszerzone informacje o stanie.
.TP
.B \-u
Bezpo¶rednio po starcie programu rozpoczyna uaktualnianie listy pakietów.
Nie mo¿na u¿ywaæ tej opcji oraz
.B \-i
jednocze¶nie.
.TP
.B \-i
Bezpo¶rednio po starcie programu wy¶wietla ekran pobierania plików 
(równowa¿ne uruchomieniu programu i wci¶niêciu "g").
Nie mo¿na u¿ywaæ tej opcji oraz
.B \-u
jednocze¶nie.

.SH OPCJE

Nastêpuj±ce opcje modyfikuj± dzia³anie powy¿szych poleceñ.
Nie ka¿de polecenie respektuje wszystkie opcje
(wiele opcji nie mia³oby sensu w po³±czeniu z pewnymi poleceniami).

Wiele opcji jest powi±zanych z dyrektywami pliku konfiguracyjnego.
Umieszczenie odpowiedniej dyrektywy w /etc/apt/apt.conf lub ~/.aptitude/config
spowoduje, ¿e aptitude zawsze bêdzie dzia³aæ tak, jakby opcja zosta³a podana.

.TP
.B \-h, \-\-help
Wy¶wietla krótki tekst pomocy.

.TP
.B \-\-version
Wy¶wietla numer wersji programu i informacje o ¶rodowisku kompilacji.

.TP
.B \-s, \-\-simulate
Wypisuje akcje, które zosta³yby wykonane, bez ich rzeczywistego przeprowadzania.
Nie s± wymagane uprawnienia administratora.

W pliku konfiguracyjnym: Aptitude::CmdLine::Simulate.

.TP
.B \-d, \-\-download-only
Tylko pobiera pakiety, bez ich instalacji czy usuwania.

W pliku konfiguracyjnym: Aptitude::CmdLine::Download-Only

.TP
.B \-P, \-\-prompt
Zawsze wy¶wietla pytanie o potwierdzenie, nawet gdy nie s± wykonywane
¿adne dodatkowe akcje.

W pliku konfiguracyjnym: Aptitude::CmdLine::Always-Prompt

.TP
.B \-y, \-\-assume-yes
Przyjmuje odpowied¼ "tak" na pytania typu tak/nie.
Nie wp³ywa na potwierdzenia szczególnie niebezpiecznych akcji, takich jak
usuwanie istotnych (Essential) pakietów.
Ma pierwszeñstwo nad -P.

W pliku konfiguracyjnym: Aptitude::CmdLine::Assume-Yes

.TP
.B \-F \fIformat\fB, \-\-display-format \fIformat\fR
Okre¶la format wy¶wietlania wyników polecenia
.BR search .
Na przyk³ad "%p %V %v" spowoduje wypisywanie nazwy pakietu, jego zainstalowanej
wersji i jego najnowszej dostêpnej wersji.
(Sekcja "COLUMNS" podrêcznika zawiera wiêcej informacji).

W pliku konfiguracyjnym: Aptitude::CmdLine::Package-Display-Format

.TP
.B \-w \fIszeroko¶æ\fB, \-\-width \fIszeroko¶æ\fR
Okre¶la szeroko¶æ wy¶wietlania wyników polecenia
.BR search .
(Domy¶lnie jest u¿ywana szeroko¶æ terminala.)

W pliku konfiguracyjnym: Aptitude::CmdLine::Package-Display-Width

.TP
.B \-f
Agesywnie próbuje naprawiæ niespe³nione zale¿no¶ci.

W pliku konfiguracyjnym: Aptitude::CmdLine::Fix-Broken

.TP
.B  \-\-with-recommends, \-\-with-suggests
Powoduj± traktowanie odpowiednio rekomendacji i sugestii jako zale¿no¶ci
przy instalowaniu nowych pakietów.
(Maj± pierwszeñstwo nad ustawieniami w /etc/apt/apt.conf i ~/.aptitude/config.)

W pliku konfiguracyjnym: Aptitude::Recommends-Important, Aptitude::Suggests-Important

.TP
.B \-\-without-recommends, \-\-without-suggests
Wy³±czaj± traktowanie odpowiednio rekomendacji i sugestii jako zale¿no¶ci
przy instalowaniu nowych pakietów.

.SH TRYB INTERAKTYWNY

Standardowo w trybie interaktywnym aptitude udostêpnia nastêpuj±ce klawisze i polecenia:
.TP
.B q
Zamyka aktualny kontekst zapisuj±c zmiany.
.TP
.B x
Zamyka aktualny kontekst bez zapisywania zmian.
.TP
.B ?
Wy¶wietla ekran pomocy.
.TP
.B Góra, k
Przesuwa kursor o jedn± pozycjê w górê.
.TP
.B Dó³, j
Przesuwa kursor o jedn± pozycjê w dó³.
.TP
.B ^
Przesuwa kursor do elementu nadrzêdnego.
.TP
.B Enter
Zwija lub rozwija grupê pakietów.
.TP
.B [
Rozwija ca³e poddrzewo pakietów.
.TP
.B ]
Zwijja ca³e poddrzewo pakietów.
.TP
.B Enter, i
Wy¶wietla informacje o pakiecie.
.TP
.B +
Zaznacza pakiet do instalacji lub uaktualnienia
albo przywraca mo¿liwo¶æ uaktualnienia wstrzymanego pakietu.
.TP
.B -
Zaznacza pakiet do usuniêcia.
.TP
.B =
Wstrzymuje uaktualnienia pakietu.
.TP
.B _
Zaznacza pakiet do wyczyszczenia (usuniêcia wraz z plikami konfiguracyjnymi).
.TP
.B L
Zaznacza pakiet do reinstalacji.
.TP
.B u
Uaktualnia listê dostêpnych pakietów.
.TP
.B g
Wykonuje wszystkie instalacje, uaktualnienia i usuniêcia pakietów.
.TP
.B Control-u
Cofa ostatni± akcjê lub grupê akcji.
.TP
.B /
Wyszukuje pakiety.
.TP
.B \\
Powtarza ostatnie wyszukiwanie.
.TP
.B D
Wy¶wietla/ukrywa dodatkowy obszar informacyjny.
.TP
.B v
Wy¶wietla dostêpne wersje pakietu.
.TP
.B d
Wy¶wietla zale¿no¶ci pakietu.
.TP
.B r
Wy¶wietla pakiety zale¿±ce od danego pakietu.
.TP
.B a
Przewija rozszerzony opis w górê.
.TP
.B z
Przewija rozszerzony opis w dó³.

.SH ZOBACZ TAK¯E
.BR apt-get (1),
.BR apt (8),
.BR /usr/share/doc/aptitude/README .
.SH AUTOR
Ta strona podrêcznika systemowego zosta³a napisana przez Daniela Burrowsa <dburrows@debian.org>.
