.\" Title: \fBaptitude-create-state-bundle\fR
.\" Author: Daniel Burrows <dburrows@debian.org>
.\" Date: 7/8/2007
.TH "\f8APTITUDE-CREATE-STATE-BUNDLE\fR" "1" "7/8/2007" "aptitude-create-state-bundle" "aptitude utilities"
.SH "NAME"
aptitude-create-state-bundle \- bundle the current aptitude state
.SH "SYNOPSIS"
\fBaptitude-create-state-bundle\fR [<\fIoptions\fR> ...] <output-file>
.SH "DESCRIPTION"
.PP
\fBaptitude-create-state-bundle\fR produces a compressed archive storing
the files that are required to replicate the current package archive
state.  The following files and directories are included in the bundle:
.IP \(bu
$HOME/.aptitude
.IP \(bu
/var/lib/aptitude
.IP \(bu
/var/lib/apt
.IP \(bu
/var/cache/apt/*.bin
.IP \(bu
/etc/apt
.IP \(bu
/var/lib/dpkg/status
.PP
The output of this program can be used as an argument to
\fBaptitude-run-state-bundle\fR(1).
.SH "OPTIONS"
.PP
\fB--help\fR
.RS
Print a brief usage message, then exit.
.RE
.PP
\fB--print-inputs\fR
.RS
Display a list of the input files and directories, then exit.  This
list is guaranteed to be up-to-date.
.RE
.SH "FILE FORMAT"
The bundle file is simply a \fBtar\fR(1) file compressed with
\fBbzip2\fR(1) or \fBgzip\fR(1), with each of the input directory
trees rooted at \(lq\fB.\fR\(rq.
.SH "SEE ALSO"
.PP
\fBaptitude-run-state-bundle\fR(1), \fBaptitude\fR(8), \fBapt(8)\fR
.SH "AUTHOR"
.PP
\fBDaniel Burrows\fR <\&dburrows@debian.org\&>
.SH "COPYRIGHT"
.PP
Copyright 2007 Daniel Burrows.

aptitude-create-state-bundle and its manpage may be copied, modified, and
redistributed in any manner whatsoever.
