from aptitude_build import NonHeaders

srcs = map(File, [
    'choice.h',
    'choice_indexed_map.h',
    'choice_set.h',
    'cost.cc',
    'cost.h',
    'cost_limits.cc',
    'cost_limits.h',
    'dummy_universe.cc',
    'dummy_universe.h',
    'dump_universe.h',
    'exceptions.h',
    'incremental_expression.cc',
    'incremental_expression.h',
    'problemresolver.h',
    'promotion_set.h',
    'resolver_undo.h',
    'sanity_check_universe.h',
    'search_graph.h',
    'solution.h',
    ])

Import('programs_env')

test = programs_env.Program(target = 'test',
                            source = ['test.cc', NonHeaders(srcs),
                                      '../util/refcounted_base.cc',
                                      ])


# This won't be distributed otherwise since it's not part of aptitude:
programs_env.Dist('test.cc')
programs_env.Alias('programs', test)

# Data to distribute:
programs_env.Dist('model.tex', 'test1.txt', 'test3.txt', 'test4.txt')
programs_env.Dist('Makefile.am', 'SConscript')

Return('srcs')
