#!/bin/bash
MANPAGE=aptitude.de.8

# this is a kludge until DocBook learns to write proper quotation marks
# in German texts;  let's at least use guillemets
sed -i "s/''/«/g;"'s/``/»/g' $MANPAGE

# and while we're on it
sed -i  's/search Suchmuster/\\fBsearch\\fR Suchmuster/' $MANPAGE
sed -i 's/\\fBaptitude\\fR help/\\fBaptitude\\fR \\fBhelp\\fR/' $MANPAGE
sed -i 's/AUTHOR/AUTOR/' $MANPAGE

head -n-2 $MANPAGE > ${MANPAGE}.tmp
cat ${MANPAGE}.tmp - >$MANPAGE <<EOF

.SH AUTOR

Diese Handbuchseite wurde von Daniel Burrows <dburrows@debian.org> verfasst.

Deutsche Übersetzung von Sebastian Kapfer <sebastian_kapfer@gmx.net>.

Bitte melden Sie Fehler.

EOF

