Import('programs_env')

# No sources because then scons tries to link them into the program!
srcs = map(File, [
    ])

programs_env.Dist(
    'cmdline_progress_display.h',
    'cmdline_progress_throttle.h',
    'teletype.cc',
    'teletype.h',
    'terminal.cc',
    'terminal.h',
    'transient_message.h',
    )

programs_env.Dist('Makefile.am', 'SConscript')

Return('srcs')
