srcs = map(File, [
    'compare_patterns.cc',
    'compare_patterns.h',
    'match.cc',
    'match.h',
    'parse.cc',
    'parse.h',
    'pattern.cc',
    'pattern.h',
    'serialize.cc',
    'serialize.h',
    ])

Return('srcs')
