Import('programs_env')

srcs = map(File, [
    'download_progress.cc',
    'download_progress.h',
    'progress.cc',
    'progress.h',
    'search_input.cc',
    'search_input.h'
    ])

programs_env.Dist('Makefile.am', 'README', 'SConscript')

SConscript(dirs = [ 'mocks' ])

Return('srcs')
