Import('programs_env')

srcs = map(File, [
    'cmine.cc',
    'cmine.h',
    'board.cc',
    'board.h',
    ])

helptexts = Glob('mine-help-??.txt') + Glob('mine-help-??_??.txt')

programs_env.Dist(helptexts)

programs_env.Dist('Makefile.am', 'SConscript')

Return('srcs')
