Import('programs_env')
programs_env.Dist('Makefile.am', 'SConscript')

sub_srcs = SConscript(dirs = [
    'apt',
    'controllers',
    'problemresolver',
    'util',
    'views',
    ])

Return('sub_srcs')
