Import('programs_env')

toplevel_srcs = map(File, [
    'model.cc',
    'model.h',
    'sidebar.h',
    'tabs_notebook.cc',
    'tabs_notebook.h',
    'view.h'
    ])

srcs = toplevel_srcs

# Distribute the build files.
programs_env.Dist('Makefile.am', 'SConscript')

Return('srcs')
