Import('programs_env')

toplevel_srcs = map(File, [
    'area.cc',
    'area.h',
    'changelog.cc',
    'changelog.h',
    'constants.h',
    'dashboardtab.cc',
    'dashboardtab.h',
    'dependency_chains_tab.cc',
    'dependency_chains_tab.h',
    'download.cc',
    'download.h',
    'dpkg_terminal.cc',
    'dpkg_terminal.h',
    'entitysummary.cc',
    'entitysummary.h',
    'entityview.cc',
    'entityview.h',
    'errortab.cc',
    'errortab.h',
    'filesview.cc',
    'filesview.h',
    'gui.cc',
    'gui.h',
    'hyperlink.cc',
    'hyperlink.h',
    'info.cc',
    'info.h',
    'notify.cc',
    'notify.h',
    'packageinformation.cc',
    'packageinformation.h',
    'packagestab.cc',
    'packagestab.h',
    'pkgview.cc',
    'pkgview.h',
    'previewtab.cc',
    'previewtab.h',
    'progress.cc',
    'progress.h',
    'resolver.cc',
    'resolver.h',
    'screenshot.cc',
    'screenshot.h',
    'screenshot_cache.cc',
    'screenshot_cache.h',
    'tab.cc',
    'tab.h',
    'treeview_cell_tooltips.cc',
    'treeview_cell_tooltips.h',
    ])

sub_srcs = SConscript(dirs = [ 'util' ])

srcs = (toplevel_srcs, sub_srcs)

programs_env.Dist('aptitude.glade')

Return('srcs')
