#!/bin/bash
# this file basically copied from fixquotes (German translation)
# and fixman (Finnish translation)

MANPAGE=aptitude.fr.8

# Guillement français pour la traduction des <quote>...</quote>
sed -i "s/''/\\ »/g;"'s/``/«\\ /g' $MANPAGE

sed -i 's/search motifs/\\fBsearch\\fR motifs/' $MANPAGE
sed -i 's/\\fBaptitude\\fR help/\\fBaptitude\\fR \\fBhelp\\fR/' $MANPAGE
sed -i 's/^\.SH NAME$/.SH NOM/' $MANPAGE

head -n-2 $MANPAGE > ${MANPAGE}.tmp
cat ${MANPAGE}.tmp - >$MANPAGE <<EOF
.SH "AUTEUR"
Daniel Burrows.

.SH "TRADUCTEURS"
Cette page de man a été originellement traduite par
Martin Quinson <martin.quison@ens-lyon.fr>. Les mises à jour sont de
Sylvain Cherrier <sylvain.cherrier@free.fr> jusqu'en 2004. Cette page est
depuis maintenue par Olivier Trichet <nive@freesurf.fr>.

EOF
