Import('docs_env')

docs_env.Dist([
        'Makefile.am',
        'aptitude-common.xsl',
        'aptitude-db2latex.xsl',
        'aptitude-html.xsl',
        'aptitude-man.xsl',
        'aptitude-txt.xsl',
        'aptitude.css',
        'fixup-text',
        'html-to-text',
        ])

SConscript(dirs = [
        'cs',
        'de',
        'en',
        'es',
        'fi',
        'fr',
        # TODO: everyone else.
        ])
