Import('docs_env')
import po4a

docs_env.Dist([
        'Makefile.am',
        'aptitude-common.xsl',
        'aptitude-db2latex.xsl',
        'aptitude-html.xsl',
        'aptitude-man.xsl',
        'aptitude-txt.xsl',
        'aptitude.css',
        'fixup-text',
        'html-to-text',
        ])

SConscript(dirs = [
        'cs',
        'de',
        'en',
        'es',
        'fi',
        'fr',
        'ja',
        # TODO: everyone else.
        ])

# NOTE: po4a must already exist; i.e., this won't work if it's an
# intermediate target.  This is a limitation of the current po4a rule.
build_po4a = docs_env.Po4AConfiguration('po4a/po4a.cfg')

docs_env.Alias('update-po', build_po4a)
docs_env.Alias('po', build_po4a)

