Import('programs_env')

toplevel_srcs = map(File, [
    'acqprogress.cc',
    'acqprogress.h',
    'apt.cc',
    'apt.h',
    'apt_undo_group.cc',
    'apt_undo_group.h',
    'aptcache.cc',
    'aptcache.h',
    'aptitude_resolver.cc',
    'aptitude_resolver.h',
    'aptitude_resolver_cost_settings.cc',
    'aptitude_resolver_cost_settings.h',
    'aptitude_resolver_cost_syntax.cc',
    'aptitude_resolver_cost_syntax.h',
    'aptitude_resolver_cost_types.cc',
    'aptitude_resolver_cost_types.h',
    'aptitude_resolver_universe.cc',
    'aptitude_resolver_universe.h',
    'aptitudepolicy.cc',
    'aptitudepolicy.h',
    'changelog_parse.cc',
    'changelog_parse.h',
    'config_signal.cc',
    'config_signal.h',
    'desc_parse.cc',
    'desc_parse.h',
    'download_install_manager.cc',
    'download_install_manager.h',
    'download_manager.cc',
    'download_manager.h',
    'download_queue.cc',
    'download_queue.h',
    'download_signal_log.cc',
    'download_signal_log.h',
    'download_update_manager.cc',
    'download_update_manager.h',
    'dump_packages.cc',
    'dump_packages.h',
    'infer_reason.cc',
    'infer_reason.h',
    'log.cc',
    'log.h',
    'parse_dpkg_status.cc',
    'parse_dpkg_status.h',
    'pkg_acqfile.cc',
    'pkg_acqfile.h',
    'pkg_changelog.cc',
    'pkg_changelog.h',
    'pkg_hier.cc',
    'pkg_hier.h',
    'resolver_manager.cc',
    'resolver_manager.h',
    'rev_dep_iterator.h',
    'screenshot.cc',
    'screenshot.h',
    'tags.cc',
    'tags.h',
    'tasks.cc',
    'tasks.h',
    ])

sub_srcs = SConscript(dirs = [
    'history',
    'matching',
    ])

srcs = (toplevel_srcs, sub_srcs)

pkg_hier_dump = programs_env.Program(target = 'pkg_hier_dump',
                                     source = [
                                         'pkg_hier.cc',
                                         'pkg_hier_dump.cc',
                                         ])

# This won't be distributed otherwise since it's not part of aptitude
# proper:
programs_env.Dist('pkg_hier_dump.cc')
programs_env.Alias('programs', pkg_hier_dump)

# Data to distribute:
programs_env.Dist('README.hier')

# Distribute the build files:
programs_env.Dist('Makefile.am', 'SConscript')

Return('srcs')
