Import('base_env')

base_env.Dist([
        'SConscript',
        'better_install.py',
        'define_directories.py',
        'distribute.py',
        'pkg_config.py',
        'test.py',
        'variant_builds.py'
        ])
