Import('programs_env')

srcs = map(File, [
    'compare3.h',
    'dense_setset.h',
    'dirent_safe.h',
    'dynamic_list.h',
    'dynamic_list_impl.h',
    'enumerator.h',
    'file_cache.cc',
    'file_cache.h',
    'immlist.h',
    'immset.h',
    'job_queue_thread.h',
    'maybe.h',
    'mut_fun.h',
    'parsers.h',
    'post_thunk.h',
    'progress_info.h',
    'refcounted_base.cc',
    'refcounted_base.h',
    'refcounted_wrapper.h',
    'safe_slot.h',
    'setset.h',
    'sqlite.cc',
    'sqlite.h',
    'temp.cc',
    'temp.h',
    'undo.cc',
    'undo.h',
    'util.cc',
    'util.h',
    ])

programs_env.Dist('Makefile.am', 'SConscript')

Return('srcs')
